#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title       : Data Science and AI for Medicine Training School with Come2Data and ScaDS.AI, 2026 # The title of the book. Will be placed in the left navbar.
author      : Matthias TÃ¤schner  # The author(s) of the book
copyright   : "2026"  # Copyright year to be placed in the footer
logo        : logo.png  # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Information about where the book exists on the web
repository:
  url: https://github.com/scads/ai4medicine-2026 # Online location of your book
  path_to_book: .  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <p>
    Copyright: Licensed <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC-BY 4.0</a> unless mentioned otherwise. 
    Contributions and feedback are welcome.
    </p>
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: '%Y-%m-%d'